### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/MPD#15]
Copied from the original PR checklist:
- [x] fix warnings
    - [x] fix clang warnings (mostly yelling at me to use `override` and `virtual` destructors properly)
- [x] accessors instead of public fields
- [x] I have no idea how to wrap long lines

**Comment by Rio6** [comment]
1. I believe all the warnings have been fixed in #3 
2. Which classes are you referring to? I looked through the headers breifly and didn't see public fields.
3. I think we're fine
```
$ find src -type f -name '*xx' -exec awk '{print length " " FILENAME}' {} \; | sort -rn | head
140 src/input/plugins/TidalInputPlugin.cxx
133 src/input/cache/Item.hxx
132 src/io/uring/Queue.hxx
132 src/input/cache/Manager.hxx
131 src/input/cache/Manager.hxx
120 src/lib/ytdl/Parser.hxx
117 src/filter/plugins/RouteFilterPlugin.cxx
115 src/input/plugins/CurlInputPlugin.cxx
113 src/RemoteTagCache.hxx
110 src/pcm/Order.cxx
```

**Comment by arcnmx** [comment]
> I believe all the warnings have been fixed in #3

There's still:
```
../src/lib/ytdl/Invoke.cxx: In static member function ‘static std::unique_ptr<Ytdl::YtdlProcess> Ytdl::YtdlProcess::Invoke(Yajl::Handle&, const char*, Ytdl::PlaylistMode)’:
../src/lib/ytdl/Invoke.cxx:71:13: warning: ‘playlist_flag’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   71 |   if (execlp("youtube-dl", "youtube-dl",
      |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |    "-Jf", "bestaudio/best", "--flat-playlist", playlist_flag, url, nullptr) < 0)
```

I believe because of the `PlaylistMode` enum not being strongly-typed, it doesn't acknowledge the switch as exhaustive. I think I had hoped `enum class` would do that but Idunno the cleanest approach otherwise.

> Which classes are you referring to? I looked through the headers breifly and didn't see public fields.

Hm looks like I already did this as part of the plugin rewrite, that was probably from before.

> I think we're fine

Cool.

**Comment by Rio6** [comment]
> There's still:
> 
> ```
> ../src/lib/ytdl/Invoke.cxx: In static member function ‘static std::unique_ptr<Ytdl::YtdlProcess> Ytdl::YtdlProcess::Invoke(Yajl::Handle&, const char*, Ytdl::PlaylistMode)’:
> ../src/lib/ytdl/Invoke.cxx:71:13: warning: ‘playlist_flag’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>    71 |   if (execlp("youtube-dl", "youtube-dl",
>       |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    72 |    "-Jf", "bestaudio/best", "--flat-playlist", playlist_flag, url, nullptr) < 0)
> ```
> 
Hm I didn't get that warning. Which branch are you on? Maybe it's there because `PlaylistMode::FULL` is still there? I did a full clean build on my side and didn't encounter ytdl-related warnings.

**Comment by arcnmx** [comment]
Hm I've been seeing it for ages, don't think I'm doing anything strange. Tried gcc 9.3 and 10.2, saw it on both. I just tried clang and don't think I saw it, but now I see new things to fix!
