### ISSUE TITLE
Whitelisted URLs

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/MPD#18]
So I think this needs another look. As much as I'd like to just throw in everything youtube-dl is known to support, I think it might need some changes:
- [x] soundcloud should probably be removed since there's already a native soundcloud plugin (even though I don't think it currently captures soundcloud.com URLs?)
- [x] twitch.tv is probably a silly default, [it has radio stations](https://www.twitch.tv/directory/game/Music) but still very niche
- [x] `music.youtube.com` should be added as well
- [ ] is there anything else that has a reasonable argument for being *added* to the list?
- [x] I already removed bandcamp because it uses user subdomains (which the code doesn't even support), it also seems like poor taste to include given the site's revenue model?

I'm thinking maybe it'll be easiest to trim this to just youtube for now?

**Comment by Rio6** [comment]
I think using youtube as the only default is good. It's youtube-dl after all.
