### ISSUE TITLE
youtube-dl process can get lost?

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/MPD#2]
Just ran into one instance where it seems the process wasn't waited on successfully when trying to play a song from my playlist:

> Sep 27 12:51:39 mpd[2132]: ERROR: Unable to download webpage: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
> ps aux|grep youtube
arc       2132  0.1  0.0      0     0 ?        Z    12:51   0:00 [youtube-dl] <defunct>
```

And the mpd process stopped responding to commands. The logic around the process management probably needs a closer look.

**Comment by arcnmx** [comment]
This might be useful for debugging/testing/reproducing, the following command seems to stall for a while before failing with the same error:
```
youtube-dl -J https://www.youtube.com/playlist?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10
```

Basically, asking for any playlist with 100+ songs seems to time it out.

**Comment by arcnmx** [comment]
Adding to this: other momentary errors like `ERROR: XXXXXXXXXX: YouTube said: Unable to extract video data` seem to make mpd get stuck and spin at 100% rather than fail gracefully? Something is pretty wrong here .-.

EDIT: adding a video that's "unavailable" on youtube (for example, 0r0mCRlfPzs) seems to consistently cause this?

**Comment by Rio6** [comment]
I'm not too familiar with managing processes, can't find where the problem might be in the current code. Trying to play "https://www.youtube.com/watch?v=0r0mCRlfPzs" did result 2 zombie process for me.

**Comment by Rio6** [comment]
Would it be here?

Invoke.cxx:113
```cpp
			} else if (errno != EINTR && errno != EAGAIN) {
				throw MakeErrno("failed to read from pipe");
			}
		} else if (res > 0) {
			handle.Parse(buffer, res);
		}
	} while (res != 0);

	handle.CompleteParse();

	if (waitpid(pid, &res, 0) < 0) {
```

If there's an error reading from youtube-dl, the program throws and don't call waitpid. And then for some reason the destructor is never called because MPD just hangs there?

I'll do some testing some time.

**Comment by arcnmx** [comment]
Did some testing, what seems to be happening is:
1. when the process exits and closes the pipe fd, epoll returns with flag `PollGroupEpoll::HANGUP`
2. `EventLoop::Run` calls `SocketMonitor::Dispatch`, which masks flags by `scheduled_flags` (which only contains `READ`), so it ignores the event and doesn't call `OnSocketReady`
3. event loop continues and epoll returns immediately again with the same flag, forever

So adding all flags (`HANGUP`+`ERROR`) to `Schedule()` should help, then `YtdlProcess::Process` will catch problems or an unexpected EOF on `read()`. Will look into it a little more and test.

**Comment by Rio6** [comment]
You beat me to it XD. I'm still at `SocketMonitor::Dispatch` wondering why `scheduled_flags` changed.

I think for error handling, you can just add `SetReady()` in `YtdlInputStream::OnError()`, so`DecoderBridge::OpenUri()` continues and gets an exception from `YtdlInputStream::Check()`.
