### ISSUE TITLE
youtube-dl takedown

### ISSUE THREAD

**Issue by Rio6** [arcnmx/MPD#21]
So um, youtube-dl was taken down by RIAA

https://github.com/ytdl-org/youtube-dl/
https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

I don't think the project will die, but I heard some distributions are already dropping it from their repository (I did't check myself). I'm not sure if upstream will merge this before it gets settled.

Thoughts? I'll still be contributing, as this is very useful and I use it day to day.

**Comment by arcnmx** [comment]
Eh it's still available for download from upstream via [yt-dl.org](https://yt-dl.org/latest). A random github takedown seems like a far cry from a real C&D; unless the project actually dies I see no reason not to continue.

The main lesson to learn here is probably to be careful of what links are included in any official examples/documentation. Other than that I don't think there's anything else really actionable here. If upstream mpd believes this is a reason to not include the plugin then we'll cross that bridge when we get there; wait for dust to settle, maintain it separately, or maybe even consider converting it to a more generic "external exec" plugin.

(of course I personally don't believe that a script that just extracts URLs from a webpage looks like anything close to copyright violation... and if the takedown stands I assume it's mostly only relevant to the US anyway? this has always felt like a grey area considering it's presumably against youtube's ToS, so really don't think it changes anything...)

**Comment by Emilot** [comment]
This is the most updated and ongoing work right now of yt-dl. 

https://github.com/blackjack4494/yt-dlc

My best guess is that this is going to be the standard one from now on.

I am waiting for mpd-youtube "edition". So i wish to keep up and make it a reality for all of us! 👍

**Comment by arcnmx** [comment]
Heh I guess that might be another argument for #7
