### ISSUE TITLE
yajl unexpected eof error

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/MPD#22]
When youtube-dl fails it typically prints an error message to stderr, then exits with a failure code. When this happens stdout is empty, so yajl errors out with an unexpected EOF parse error.

- [x] Should the plugin call yajl parse finish() only *after* waiting and checking for exit code?
- [ ] Should it capture stderr to display error messages over the protocol instead of just "process exited with non-zero code" or whatever?

(I have no strong opinions either way but both items seem reasonable enough - though reading stderr seems a little annoying and maybe unnecessary)

**Comment by Rio6** [comment]
I think it'd be nice to see error message from youtbe-dl, or at least a message indicating that youtube-dl failed. But that's probably not a high priority right now.

**Comment by arcnmx** [comment]
It might be nice to capture the stderr message, but yeah agreeing that's pretty low priority for now. It's not unusual to check mpd's logs for more details when something goes wrong anyway.
