### ISSUE TITLE
resuming playback sometimes fails

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/MPD#6]
Occasionally a short while after resuming playback, mpd will suddenly skip to the next track. Presumably this happens because the input stream's URL has expired in the time since it was paused. The plugin should be able to detect and recover from these failures - but still be able to bail out on persistent failures of course. mpv seems to have similar logic built in?

Also, move to `ProxyInputStream` if possible.

**Comment by Rio6** [comment]
Hm, I'm thinking of a way to be able to distinguish between expired url vs other failures. Maybe we can make YtdlInputStream to get another url when the inner stream failed, if a certain amount of time has passed?

**Comment by arcnmx** [comment]
Including any sort of time-sensitive code seems like something to avoid, it will probably be messy. It looks like the expiry time is encoded into the URL (a quick test shows they're valid for 6 hours?), but we can't really count on that...

Maybe if we're lucky it errors out with a sensible status code like 408/410/??? that can be used to trigger a retry?

EDIT: youtube looks like 403 Forbidden once it expires... So if we can't consistently tell then we might have to set up some sort of error counter that's cleared any time a request succeeds / data is received... and retry at least once on failures?

**Comment by Rio6** [comment]
Parsing URL/response probably won't work for every single extractors youtube-dl support so probably not the best idea.

I guess a retry counter is the best we can do.

**Comment by Rio6** [comment]
I've made YtdlInputStream inhertit from ProxyInputStream in https://github.com/Rio6/MPD/tree/ytdl. I'll add the retry counter later.

Update: the code for retrying is pushed too

**Comment by Rio6** [comment]
#24 should fix this, although I haven't actually tried pausing a song for a long time. I'll probably do that in the next few days when I remember and see if it works.

**Comment by Rio6** [comment]
I paused a song for 11 hours and itstill plays as expected. Let's call this issue done.

BTW, it might be good to do another rebase, we're lots of commits behind again :)

**Comment by arcnmx** [comment]
Sorry I've been dead for ages, will try to get to that over the next few days. I've been using it all year and am pretty happy with how it's been working! I'll check if there's anything major to update to, and also put up a 0.22.7 branch too.
