### ISSUE TITLE
configurable executable path

### ISSUE THREAD

**Issue by arcnmx** [arcnmx/MPD#7]
Can (and should?) we make the `youtube-dl` binary path configurable since it's a runtime dependency? `PATH` can always still be modified of course but... still might be useful.

- [x] `youtube-dl` path configuration variable
- [x] audio `format` configuration variable
- [x] `config_file` configuration variable

**Comment by arcnmx** [comment]
Also related feature: custom additional arguments. Passing a `--netrc` file could be useful for example. This can also be done via a wrapper in PATH though, so isn't strictly necessary... There's also the youtube-dl config file that accomplishes this.

**Comment by Rio6** [comment]
That's a good idea. Should the program switch betweem `execlp` and `execl` depending on whether a youtube-dl path is specified?

**Comment by Rio6** [comment]
Sorry, my bad. `execlp` works with path too.

**Comment by Rio6** [comment]
Do you think it's better to only implement only some options in the config, like
```
input {
    plugin: "youtube-dl"
    netrc: "yes"
    proxy: "stuff"
}
```
Or let them pass a string
```
input {
    plugin: "youtube-dl"
    params: "--netrc --proxy stuff"
}
```
Looking at youtube-dl man page, it looks like most of the options won't be useful, so maybe the first approach is better. I'm not sure what options would need to be implemented, though.

**Comment by arcnmx** [comment]
So I do think this is something that can wait until after core functionality is upstreamed for the most part - for either approach once it's available for configuration, you're kind of stuck with supporting it. Starting with less seems more neutral, and we might just find that options like netrc or proxy would be easier to set globally using [~/.config/youtube-dl/config](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration). I kind of like the individual options (first approach), but also feel like less may just be simpler.

Another thought: currently the plugin requests `--format bestaudio`, there may be reasons to want to customize that?

**Comment by Rio6** [comment]
Yeah ok, let's first focus on merging into upstream before adding this feature.

~~The first option is also easier to implement, since we don't need to separate a single string into arrays when passed to `execlp`. I don't think there will be a lot of options needed. Some options I think might be useful: `--netrc`, `--username`, `--password`, `proxy`.~~

When looking through man page, I also found that there's a `--config-location` option, which sets which custom config file youtube-dl will use. I think just have a config entry for that would be enough. Like
```
input {
    plugin: "youtube-dl"
    path: "/usr/local/bin/youtube-dl"
    config_file: "~/.config/mpd/youtube-dl.conf
}
```
 We'll need to make sure mpd will be able to handle errors with misconfigured youtube-dl, however.

BTW, what's the todo list to get this merged in upstream? I think #2, #6 and documentation?

**Comment by arcnmx** [comment]
Yeah in terms of config item priority I think it goes something like...
1. Anything currently hard-coded into the plugin should definitely become a config option
    - `youtube-dl` binary name/path, though `$PATH` does exist so you could argue it's not a blocker
    - `bestaudio` format selection
    - anything else I'm missing here? flat v full playlist modes possibly, but... I think we can live exclusively with flat mode for now.
2. Other specific options like `netrc` etc
3. I kind of like the idea of punting the rest off to `config_file`, but that makes `2` mostly unnecessary...
4. `params` does complicate things due to quoting and spaces, so yeah, I mostly wouldn't think about that for now. It's also covered by `config_file` anyway.

Personally speaking, just being able to change the `youtube-dl` binary is good enough for me, because I can always just pass extra customized options in a wrapper script or something.

> We'll need to make sure mpd will be able to handle errors with misconfigured youtube-dl, however

I think that's mostly just covered by fixing #2? though maybe we could be fancy and return error messages over the protocol rather than stderr...

> BTW, what's the todo list to get this merged in upstream? I think #2, #6 and documentation?

Hm I think GitHub has a way to group issues into milestones, maybe I'll do that! But yeah, mostly just those and then a little cleanup after.

EDIT: [done](https://github.com/arcnmx/MPD/projects/1), migrated the remainder of the checklist from the original PR to github issues.

**Comment by Rio6** [comment]
I think MPD uses different config blocks for input and playlist plugins? That might be a bit annoying for the user.

The github project looks nice.

**Comment by arcnmx** [comment]
> I think MPD uses different config blocks for input and playlist plugins? That might be a bit annoying for the user.

Given that the playlist plugin can't function without the input plugin, and (I believe?) the config state needs to be global anyway... It's probably not the end of the world to just require all common configuration to be done on the input plugin. If playlist-specific options exist (pretend Full vs Flat are still a thing) then those could go under the playlist plugin.

**Comment by Rio6** [comment]
The problem is that the plugins (input and playlist) only get their own config block when being initialized, so playlist plugin can't read input plugin's config.

Making YtdlInit a singleton can get around that, so input plugin can initlaize it, and both plugins can share the same config. Though I'm not sure if that's the best way to do it. Changing the MPD code to store config globally doesn't sound like the right way either.

If we do it the intended way, it would be that the two plugins use different config blocks, and the user would need to specify the same thing twice. Which can be confusing to use.

I personally think singleton YtdlInit is the best option out of the 3. What you think?

**Comment by arcnmx** [comment]
Yup that's what I meant by global above, a singleton initialized by the input plugin makes the most sense to me.

**Comment by Rio6** [comment]
Working code on this branch https://github.com/Rio6/MPD/tree/ytdl-configs

Still needs to add documentations. I'll probably wait until #20 is done, then rebase into that.

**Comment by arcnmx** [comment]
> Working code on this branch https://github.com/Rio6/MPD/tree/ytdl-configs

So I've kind of applied this but based on ad098b8375a9847956ad775a9df290b033e24f6a instead to use a shared `YtdlInit` class.

> I'll probably wait until #20 is done, then rebase into that.

You shouldn't need to wait? I've reverted to the quick workaround for now which should be working fine.

Bikeshed: config name `command` seems fine, but could also be `path`? `command` kind of implies that it might support spaces and be parsed by a shell for args (someone might try to set it to `command = youtube-dl --netrc` or whatever). Not a big deal though.

**Comment by Rio6** [comment]
`executable` maybe? Since it can also be a command in PATH. I don't have opinion oo if any of them is better personally.

And yes ytdl branch is working, my bad for not checking.

**Comment by arcnmx** [comment]
`executable` sounds good to me!
